### ISSUE TITLE
Actual Connection and setup?

### ISSUE THREAD

**Issue by markmghali** [awawa-dev/HyperSerialWLED#3]
This is totally my ignorance but how do you actually set this up with HyperHDR over USB? 

I have used hyperion-ng with WLED over network and worked well. I am looking to enhance my setup with your two projects HyperHDR and HyperSerialWLED.

I am using a QuinLED DigUno with a Raspberry Pi 2 and a webcam pointed at my TV. 

I just don't understand the actually connection over USB Serial?  

Thank you for these awesome projects

**Comment by awawa-dev** [comment]
Thanks :-)

In fact it's quite simple: just connect you ESP board which runs WLED/HyperserialWLED to Raspberry Pi 2 USB port, configure it (adalight driver: set 2 000 000 speed and AWA protocol enable for HyperserialWLED or 115 200 speed and AWA protocol disabled for WLED) and that's all if you have already your LED strip configured properly in WLED www interface. The low level protocol is in fact: serial port over USB connection.
You must make sure that you  ESP board has ch340g or cp2104 chip on board: For example here https://quinled.info/quinled-esp32/ that large chip on the right at the bottom is probably ch340g.
